# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import rf_service_pb2 as rf__service__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in rf_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RandomForestWorkerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.TrainSubForest = channel.unary_unary(
                '/RandomForestWorker/TrainSubForest',
                request_serializer=rf__service__pb2.TrainRequest.SerializeToString,
                response_deserializer=rf__service__pb2.TrainResponse.FromString,
                _registered_method=True)
        self.Predict = channel.unary_unary(
                '/RandomForestWorker/Predict',
                request_serializer=rf__service__pb2.PredictRequest.SerializeToString,
                response_deserializer=rf__service__pb2.PredictResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/RandomForestWorker/HealthCheck',
                request_serializer=rf__service__pb2.Empty.SerializeToString,
                response_deserializer=rf__service__pb2.HealthStatus.FromString,
                _registered_method=True)


class RandomForestWorkerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def TrainSubForest(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Predict(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RandomForestWorkerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'TrainSubForest': grpc.unary_unary_rpc_method_handler(
                    servicer.TrainSubForest,
                    request_deserializer=rf__service__pb2.TrainRequest.FromString,
                    response_serializer=rf__service__pb2.TrainResponse.SerializeToString,
            ),
            'Predict': grpc.unary_unary_rpc_method_handler(
                    servicer.Predict,
                    request_deserializer=rf__service__pb2.PredictRequest.FromString,
                    response_serializer=rf__service__pb2.PredictResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=rf__service__pb2.Empty.FromString,
                    response_serializer=rf__service__pb2.HealthStatus.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'RandomForestWorker', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('RandomForestWorker', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RandomForestWorker(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def TrainSubForest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/RandomForestWorker/TrainSubForest',
            rf__service__pb2.TrainRequest.SerializeToString,
            rf__service__pb2.TrainResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Predict(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/RandomForestWorker/Predict',
            rf__service__pb2.PredictRequest.SerializeToString,
            rf__service__pb2.PredictResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/RandomForestWorker/HealthCheck',
            rf__service__pb2.Empty.SerializeToString,
            rf__service__pb2.HealthStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
