# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: rf_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'rf_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10rf_service.proto\"\xe7\x01\n\x0cTrainRequest\x12\x10\n\x08model_id\x18\x01 \x01(\t\x12\x14\n\x0csubforest_id\x18\x02 \x01(\t\x12\x17\n\x0f\x64\x61taset_s3_path\x18\x03 \x01(\t\x12\x0c\n\x04seed\x18\x04 \x01(\x05\x12\x14\n\x0cn_estimators\x18\x05 \x01(\x05\x12\x11\n\ttask_type\x18\x06 \x01(\x05\x12\x11\n\tmax_depth\x18\x07 \x01(\x05\x12\x14\n\x0cmax_features\x18\x08 \x01(\t\x12\x11\n\tcriterion\x18\t \x01(\t\x12\x11\n\tskip_rows\x18\n \x01(\x05\x12\x10\n\x08num_rows\x18\x0b \x01(\x05\"c\n\rTrainResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x13\n\x0btrees_built\x18\x02 \x01(\x05\x12\x15\n\rmodel_s3_path\x18\x03 \x01(\t\x12\x15\n\rerror_message\x18\x04 \x01(\t\"]\n\x0ePredictRequest\x12\x10\n\x08model_id\x18\x01 \x01(\t\x12\x14\n\x0csubforest_id\x18\x02 \x01(\t\x12\x10\n\x08\x66\x65\x61tures\x18\x03 \x03(\x02\x12\x11\n\ttask_type\x18\x04 \x01(\x05\"3\n\x0fPredictResponse\x12\r\n\x05votes\x18\x01 \x03(\x05\x12\x11\n\testimates\x18\x02 \x03(\x02\"\x07\n\x05\x45mpty\"\x1d\n\x0cHealthStatus\x12\r\n\x05\x61live\x18\x01 \x01(\x08\x32\x99\x01\n\x12RandomForestWorker\x12/\n\x0eTrainSubForest\x12\r.TrainRequest\x1a\x0e.TrainResponse\x12,\n\x07Predict\x12\x0f.PredictRequest\x1a\x10.PredictResponse\x12$\n\x0bHealthCheck\x12\x06.Empty\x1a\r.HealthStatusb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rf_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TRAINREQUEST']._serialized_start=21
  _globals['_TRAINREQUEST']._serialized_end=252
  _globals['_TRAINRESPONSE']._serialized_start=254
  _globals['_TRAINRESPONSE']._serialized_end=353
  _globals['_PREDICTREQUEST']._serialized_start=355
  _globals['_PREDICTREQUEST']._serialized_end=448
  _globals['_PREDICTRESPONSE']._serialized_start=450
  _globals['_PREDICTRESPONSE']._serialized_end=501
  _globals['_EMPTY']._serialized_start=503
  _globals['_EMPTY']._serialized_end=510
  _globals['_HEALTHSTATUS']._serialized_start=512
  _globals['_HEALTHSTATUS']._serialized_end=541
  _globals['_RANDOMFORESTWORKER']._serialized_start=544
  _globals['_RANDOMFORESTWORKER']._serialized_end=697
# @@protoc_insertion_point(module_scope)
